export const PROFILER_STYLE_ID = 'dsh-plugin-profiler/client'

export const PROFILER_STYLES = [
  '.dpp-root { display:flex; flex-direction:column; gap:16px; width:100%; max-width:920px; color:var(--dsw-alias-label-primary); }',
  '.dpp-hero { display:flex; align-items:flex-start; justify-content:space-between; gap:20px; padding:18px; border:1px solid var(--dsw-alias-border-l2); border-radius:12px; background:linear-gradient(135deg, color-mix(in srgb, var(--dsw-alias-state-business-primary) 8%, transparent), transparent 58%), var(--dsw-alias-bg-layer-3); }',
  '.dpp-heading { min-width:0; }',
  '.dpp-eyebrow { margin:0 0 4px; color:var(--dsw-alias-state-business-primary); font-size:11px; line-height:16px; font-weight:700; letter-spacing:.08em; text-transform:uppercase; }',
  '.dpp-title { margin:0; font-size:18px; line-height:26px; font-weight:650; }',
  '.dpp-subtitle { margin:5px 0 0; max-width:620px; color:var(--dsw-alias-label-secondary); font-size:13px; line-height:20px; }',
  '.dpp-actions { display:flex; flex:none; align-items:center; gap:8px; }',
  '.dpp-badge { display:inline-flex; align-items:center; min-height:24px; border-radius:999px; padding:2px 9px; background:color-mix(in srgb, var(--dsw-alias-state-warning-primary) 13%, transparent); color:var(--dsw-alias-state-warning-primary); font-size:11px; line-height:18px; font-weight:600; white-space:nowrap; }',
  '.dpp-button { min-height:30px; border:1px solid var(--dsw-alias-border-l2); border-radius:7px; padding:4px 11px; background:var(--dsw-alias-bg-layer-1); color:var(--dsw-alias-label-primary); font:inherit; font-size:12px; cursor:pointer; }',
  '.dpp-button:hover { background:var(--dsw-alias-interactive-bg-hover); }',
  '.dpp-button:focus-visible, .dpp-search:focus-visible { outline:2px solid var(--dsw-alias-state-business-primary); outline-offset:2px; }',
  '.dpp-metrics { display:grid; grid-template-columns:repeat(4, minmax(0, 1fr)); gap:10px; }',
  '.dpp-metric { min-width:0; border:1px solid var(--dsw-alias-border-l2); border-radius:10px; padding:13px 14px; background:var(--dsw-alias-bg-layer-3); }',
  '.dpp-metric-label { display:block; color:var(--dsw-alias-label-tertiary); font-size:11px; line-height:17px; }',
  '.dpp-metric-value { display:block; margin-top:3px; overflow:hidden; font-size:20px; line-height:28px; font-weight:650; font-variant-numeric:tabular-nums; text-overflow:ellipsis; white-space:nowrap; }',
  '.dpp-metric-note { display:block; overflow:hidden; color:var(--dsw-alias-label-tertiary); font-size:11px; line-height:17px; text-overflow:ellipsis; white-space:nowrap; }',
  '.dpp-notice { margin:0; border-left:3px solid var(--dsw-alias-state-warning-primary); border-radius:0 8px 8px 0; padding:9px 12px; background:color-mix(in srgb, var(--dsw-alias-state-warning-primary) 7%, transparent); color:var(--dsw-alias-label-secondary); font-size:12px; line-height:19px; }',
  '.dpp-filters { display:flex; flex-wrap:wrap; gap:6px; }',
  '.dpp-chip { min-height:28px; border:1px solid var(--dsw-alias-border-l2); border-radius:999px; padding:3px 12px; background:var(--dsw-alias-bg-layer-1); color:var(--dsw-alias-label-secondary); font:inherit; font-size:12px; font-variant-numeric:tabular-nums; cursor:pointer; white-space:nowrap; }',
  '.dpp-chip:hover { background:var(--dsw-alias-interactive-bg-hover); }',
  '.dpp-chip:focus-visible { outline:2px solid var(--dsw-alias-state-business-primary); outline-offset:2px; }',
  '.dpp-chip[data-active="true"] { border-color:transparent; background:color-mix(in srgb, var(--dsw-alias-state-business-primary) 14%, transparent); color:var(--dsw-alias-state-business-primary); font-weight:600; }',
  '.dpp-origin { display:inline-flex; align-items:center; min-height:22px; border-radius:6px; padding:2px 8px; background:var(--dsw-alias-bg-layer-1); color:var(--dsw-alias-label-tertiary); font-size:11px; white-space:nowrap; }',
  '.dpp-origin[data-origin="user"] { background:color-mix(in srgb, var(--dsw-alias-state-business-primary) 12%, transparent); color:var(--dsw-alias-state-business-primary); font-weight:600; }',
  '.dpp-toolbar { display:flex; align-items:center; justify-content:space-between; gap:12px; }',
  '.dpp-search { box-sizing:border-box; width:min(360px, 100%); height:34px; border:1px solid var(--dsw-alias-border-l2); border-radius:8px; padding:0 11px; outline:none; background:var(--dsw-alias-bg-layer-1); color:var(--dsw-alias-label-primary); font:inherit; font-size:12px; }',
  '.dpp-search::placeholder { color:var(--dsw-alias-label-tertiary); }',
  '.dpp-meta { color:var(--dsw-alias-label-tertiary); font-size:11px; line-height:17px; text-align:right; }',
  '.dpp-table-wrap { overflow:auto; border:1px solid var(--dsw-alias-border-l2); border-radius:10px; background:var(--dsw-alias-bg-layer-3); }',
  '.dpp-table { width:100%; min-width:720px; border-collapse:collapse; font-size:12px; line-height:18px; }',
  '.dpp-table th { padding:9px 12px; border-bottom:1px solid var(--dsw-alias-border-l2); background:var(--dsw-alias-bg-layer-1); color:var(--dsw-alias-label-tertiary); font-weight:600; text-align:left; white-space:nowrap; }',
  '.dpp-table td { padding:11px 12px; border-bottom:1px solid var(--dsw-alias-border-l2); vertical-align:middle; }',
  '.dpp-table tbody tr:last-child td { border-bottom:0; }',
  '.dpp-plugin { display:flex; flex-direction:column; min-width:190px; max-width:320px; }',
  '.dpp-plugin strong { display:flex; align-items:center; gap:6px; min-width:0; font-size:13px; line-height:19px; }',
  '.dpp-name { overflow:hidden; text-overflow:ellipsis; white-space:nowrap; }',
  '.dpp-plugin code { overflow:hidden; color:var(--dsw-alias-label-tertiary); font-family:var(--ds-font-family-code); font-size:10px; line-height:16px; text-overflow:ellipsis; white-space:nowrap; }',
  '.dpp-tag { flex:none; border-radius:5px; padding:1px 6px; background:var(--dsw-alias-bg-layer-1); color:var(--dsw-alias-label-tertiary); font-size:10px; line-height:16px; font-weight:600; white-space:nowrap; }',
  '.dpp-tag[data-tag="reload"] { background:color-mix(in srgb, var(--dsw-alias-state-warning-primary) 13%, transparent); color:var(--dsw-alias-state-warning-primary); }',
  '.dpp-cell { display:flex; flex-direction:column; gap:1px; }',
  '.dpp-sub { overflow:hidden; max-width:180px; color:var(--dsw-alias-label-tertiary); font-size:10px; line-height:15px; text-overflow:ellipsis; white-space:nowrap; }',
  '.dpp-sub[data-confident="false"] { color:var(--dsw-alias-label-tertiary); font-style:italic; opacity:.6; }',
  '.dpp-number { font-variant-numeric:tabular-nums; white-space:nowrap; }',
  '.dpp-duration[data-complete="false"] { color:var(--dsw-alias-label-tertiary); }',
  // 容器条目的耗时来自子条目,弱化它,免得它在榜单上冒充最慢的插件。
  '.dpp-table tbody tr[data-group="true"] { background:color-mix(in srgb, var(--dsw-alias-label-tertiary) 4%, transparent); }',
  '.dpp-table tbody tr[data-group="true"] .dpp-name { color:var(--dsw-alias-label-secondary); font-weight:500; }',
  '.dpp-outcome { display:inline-flex; align-items:center; min-height:22px; border-radius:999px; padding:2px 8px; background:var(--dsw-alias-bg-layer-1); color:var(--dsw-alias-label-secondary); font-size:11px; white-space:nowrap; }',
  '.dpp-outcome[data-outcome="active"] { background:color-mix(in srgb, var(--dsw-alias-state-success-primary) 10%, transparent); color:var(--dsw-alias-state-success-primary); }',
  '.dpp-outcome[data-outcome="failed"] { background:color-mix(in srgb, var(--dsw-alias-state-error-primary) 10%, transparent); color:var(--dsw-alias-state-error-primary); }',
  '.dpp-status { margin:0; padding:22px 4px; color:var(--dsw-alias-label-tertiary); font-size:13px; line-height:20px; }',
  '.dpp-failure { display:flex; align-items:flex-start; justify-content:space-between; gap:12px; border:1px solid color-mix(in srgb, var(--dsw-alias-state-error-primary) 30%, transparent); border-radius:10px; padding:12px; background:color-mix(in srgb, var(--dsw-alias-state-error-primary) 6%, transparent); color:var(--dsw-alias-state-error-primary); }',
  '.dpp-failure-copy { min-width:0; }',
  '.dpp-failure .dpp-status { padding:0; color:inherit; }',
  '.dpp-error-detail { display:block; margin-top:4px; color:var(--dsw-alias-label-secondary); font-family:var(--ds-font-family-code); font-size:11px; line-height:17px; overflow-wrap:anywhere; white-space:pre-wrap; }',
  '@media (max-width:760px) { .dpp-hero { flex-direction:column; } .dpp-actions { width:100%; justify-content:space-between; } .dpp-metrics { grid-template-columns:repeat(2, minmax(0, 1fr)); } .dpp-toolbar { align-items:flex-start; flex-direction:column; } .dpp-search { width:100%; } .dpp-table { min-width:640px; } }',
].join('\n')
